### ISSUE TITLE
Move logs to project specific directory

### ISSUE THREAD

**Issue by slsevilla** [CCRGeneticsBranch/khanlab_ngs_pipeline#11]
Problem: Currently all logs are being deposited in one directory. This makes review of any errors and general management impossible given the large number of files. 

Solution: All project logs should be within the /project/dir/logs/run_date directory.

Improvements of the solution:
- all for zipping of old logs, saving space
- all for easier review of error logs by run; repeated runs of the same project will maintain their logs separately
- ability to easily parse through (IE grep) logs for errors or other completion stats, impossible to do currently

**Comment by slsevilla** [comment]
Assigning to @vinegang  - not sure if this was done or needed still. If it's not, please close!

**Comment by vinegang** [comment]
We dont need this now, as the pipeline is moving to nextflow
